# Make sure to install vagrant-vbguest plugin.
#
# vagrant plugin install vagrant-vbguest

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"
  
  config.vm.define "tor" do |instance|
    instance.vm.provider "virtualbox" do |vm|
      vm.name = "ubuntu-tor"
    end

    instance.vm.hostname = "ubuntu-tor"
  end

  config.vm.provision "file" do |file|
    file.source = "torrc"
    file.destination = "/tmp/torrc"
  end

  config.vm.provision "file" do |file|
    file.source = "hidden-service.conf"
    file.destination = "/tmp/hidden-service.conf"
  end

  config.vm.provision "file" do |file|
    file.source = "clearnet-service.conf"
    file.destination = "/tmp/clearnet-service.conf"
  end
  
  config.vm.boot_timeout = 900
  config.vm.provision "shell", path: "config-machine.sh"
end